server:
  port: 8083

spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    username: sunny
    password: PHW#84#jeor

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
